const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const stub=()=>({addEventListener(){},textContent:'',innerHTML:'',src:''});
function prepare(search,isListing=true){const nodes=new Map();const doc={querySelector(s){if(s==='#mirror-grid'&&!isListing)return null;if(!nodes.has(s))nodes.set(s,stub());return nodes.get(s)}};const c={window:{},document:doc,location:{search,replace(url){this.redirect=url}},URLSearchParams};vm.createContext(c);for(const file of ['mirror-data.js','catalogue-data.js','furniture-filters.js','art-filters.js','lighting-filters.js','textiles-filters.js','accessories-filters.js','artbeat-filters.js','made-to-order-filters.js','clocks-filters.js','catalogue-context.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),c);return{c,nodes};}
const clock=prepare('?dept=Clocks');assert.equal(clock.c.window.MIRROR_PRODUCTS.length,14);assert.equal(clock.nodes.get('#category-title').textContent,'Clocks');assert(clock.c.window.CATALOGUE_CONTEXT.labels.type);assert(clock.c.window.MIRROR_PRODUCTS.every(p=>p.image&&p.dept==='Clocks'));
for(const sub of ['Wall Clocks','Cuckoo Clocks','Mantel Clocks']){const x=prepare('?dept=Clocks&sub='+encodeURIComponent(sub));assert(x.c.window.MIRROR_PRODUCTS.length>0);assert(x.c.window.MIRROR_PRODUCTS.every(p=>p.type===sub));assert.equal(x.nodes.get('#category-title').textContent,sub);}
for(const dept of ['Furniture','Lighting','Outdoor Living','Home Accessories','Soft Furnishings','Mattresses','Art','Greeting Cards']){const x=prepare('?dept='+encodeURIComponent(dept));assert(x.c.window.MIRROR_PRODUCTS.length>0);assert(x.c.window.MIRROR_PRODUCTS.every(p=>p.dept===dept));assert.equal(x.nodes.get('#category-title').textContent,dept);}
assert.equal(prepare('?dept=Lighting&sub=Floor+Lamps').c.window.MIRROR_PRODUCTS.length,0);
assert.equal(prepare('?route=Sale').c.window.MIRROR_PRODUCTS.length,0);
const detail=prepare('?sku=AMC13003&dept=Clocks',false);assert.equal(detail.c.window.CATALOGUE_CONTEXT.product.name,'Cuckoo Wall Clock in Forest');assert(detail.c.window.CATALOGUE_CONTEXT.product.images.length>1);
console.log('Passed: all 9 category contexts, 14 real clocks, wall/cuckoo/mantel subroutes, empty states and clock detail galleries.');

const seating=prepare('?dept=Furniture&group=Seating');assert(seating.c.window.MIRROR_PRODUCTS.length);assert(seating.c.window.MIRROR_PRODUCTS.every(p=>['Sofas','Sofa Beds','Armchairs & Accent Chairs','Dining Chairs','Bar Stools','Benches','Footstools & Pouffes'].includes(p.type)));
assert(prepare('?dept=Furniture&sub=Sofa+Beds').c.window.MIRROR_PRODUCTS.some(p=>p.name==='Haven Sofa Bed'));
assert(prepare('?dept=Furniture&sub=Cabinets').c.window.MIRROR_PRODUCTS.some(p=>p.name==='Lowry Storage Cabinet'));
assert(prepare('?dept=Outdoor+Living&sub=Bistro+Sets').c.window.MIRROR_PRODUCTS.some(p=>p.name==='Seabrook Bistro Set'));
assert.equal(prepare('?dept=Made+to+Order').c.window.MIRROR_PRODUCTS.length,0);
const tree=JSON.parse(fs.readFileSync('navigation-taxonomy.json'));const destinations=new Set();for(const menu of tree){for(const group of menu.groups){const u=new URL(group.href,'https://preview.test');if(u.pathname.endsWith('catalogue.html')){const x=prepare(u.search),dept=u.searchParams.get('dept'),name=u.searchParams.get('group');assert(x.c.window.GALLERY_CATALOGUE.departments[dept]);if(name)assert(x.c.window.GALLERY_CATALOGUE.departments[dept].groups.some(g=>g[0]===name));}for(const [label,href] of group.links){assert(!destinations.has(href),'Duplicate menu destination: '+label);destinations.add(href);const u=new URL(href,'https://preview.test');if(u.pathname.endsWith('catalogue.html'))assert(prepare(u.search).c.window.GALLERY_CATALOGUE.departments[u.searchParams.get('dept')]);}}}
console.log('Passed: canonical menu destinations, group membership, corrected sofa/cabinet/bistro routes and honest Made to Order empty state.');

for(const group of ['Cushions & Throws','Bedding','Kitchen & Table Linen','Rugs & Practical Textiles','Outdoor Textiles']){const x=prepare('?dept=Soft+Furnishings&group='+encodeURIComponent(group));assert.equal(x.c.window.CATALOGUE_CONTEXT.title,group);assert(x.c.window.CATALOGUE_CONTEXT.facetOptions.type.length>0);}const kitchen=prepare('?dept=Soft+Furnishings&sub=Kitchen+Textiles');assert(kitchen.c.window.GalleryCatalogueRouting.routeMatch({type:'Kitchen Apron'},'Kitchen Textiles'));assert(!kitchen.c.window.GalleryCatalogueRouting.routeMatch({type:'Rugs'},'Kitchen Textiles'));assert(kitchen.c.window.CATALOGUE_CONTEXT.facetOptions.type.includes('Table Linen'));assert(!('filling' in kitchen.c.window.CATALOGUE_CONTEXT.labels));console.log('Passed: five Textiles group routes, precise filter options and kitchen membership.');

const outdoors=prepare('?dept=Outdoor+Living&sub=Bistro+Tables+%26+Sets');assert(outdoors.c.window.MIRROR_PRODUCTS.some(p=>p.name==='Seabrook Bistro Set'));assert(outdoors.c.window.GalleryCatalogueRouting.routeMatch({dept:'Outdoor Living',type:'Stool'},'Stools'));const outdoorMirrors=prepare('?dept=Outdoor+Living&sub=Outdoor+Mirrors');assert(outdoorMirrors.c.window.MIRROR_PRODUCTS.every(p=>p.dept==='Outdoor Living'));console.log('Passed: Outdoor bistro aggregation, duplicate stool mapping and outdoor-only scope.');
